// The vendored-paths catalog: which trees and files an agent may read but never
// patch. Installed dependencies, tool caches, build output, lockfiles, and the
// Git object store all get regenerated by a tool; hand edits there "fix" a
// symptom in a copy that the next install throws away. Data only; ../match
// compiles it. To open a family, delete its entry; to lift the guard for one
// session, the user runs `/access-guard vendored off`.

import type { VendoredEntry } from "./types";

const ESCAPE =
  "If this edit is deliberate, the user can run `/access-guard vendored off` for this session.";

export const VENDORED_CATALOG: readonly VendoredEntry[] = [
  {
    id: "deps",
    label: "an installed dependency tree",
    guidance:
      "Never patch a dependency in place: fix the calling code, pin or upgrade the package, " +
      "or carry a patch through the package manager (bun patch / patch-package / uv override). " +
      ESCAPE,
    dirs: [
      "node_modules",
      "bower_components",
      ".venv",
      "venv",
      ".tox",
      ".nox",
      "site-packages",
      "dist-packages",
      "vendor",
      "Pods",
      ".terraform",
      ".bun",
    ],
    files: [],
    removable: true,
  },
  {
    id: "cache",
    label: "a tool cache",
    guidance:
      "A cache is rebuilt by the tool that owns it: clear it with that tool's own command " +
      "or remove the whole directory, never edit what is inside. " +
      ESCAPE,
    dirs: [
      "__pycache__",
      ".pytest_cache",
      ".ruff_cache",
      ".mypy_cache",
      ".cache",
      ".turbo",
      ".parcel-cache",
      ".gradle",
      ".eggs",
    ],
    files: [],
    removable: true,
  },
  {
    id: "build",
    label: "build output",
    guidance:
      "Build output is produced from source: change the source and rebuild, never the artifact. " +
      ESCAPE,
    dirs: [
      "dist",
      "build",
      "coverage",
      "htmlcov",
      "target",
      ".next",
      ".nuxt",
      ".svelte-kit",
      "*.egg-info",
    ],
    files: [],
    removable: true,
  },
  {
    id: "lock",
    label: "a package-manager lockfile",
    guidance:
      "A lockfile is written only by its package manager: change the manifest and run the " +
      "install/lock command (bun install · uv lock · cargo update …), never edit it by hand. " +
      ESCAPE,
    dirs: [],
    files: [
      "bun.lock",
      "bun.lockb",
      "package-lock.json",
      "npm-shrinkwrap.json",
      "yarn.lock",
      "pnpm-lock.yaml",
      "uv.lock",
      "poetry.lock",
      "Pipfile.lock",
      "pdm.lock",
      "Cargo.lock",
      "Gemfile.lock",
      "composer.lock",
      "go.sum",
      "flake.lock",
      "mix.lock",
      "Podfile.lock",
      "packages.lock.json",
      "pubspec.lock",
      ".terraform.lock.hcl",
    ],
    removable: true,
  },
  {
    id: "git",
    label: "the Git object store",
    guidance:
      "Never write under .git/ by hand — every git command already maintains it. " +
      "Use `git config`, `git update-index`, or the porcelain command that owns the change. " +
      ESCAPE,
    dirs: [".git"],
    files: [],
    removable: false,
  },
];
